---

- name: Allow SSH in UFW
  ufw: rule=allow port=22 proto=tcp

- name: Set firewall default policy
  ufw: state=enabled policy=reject
  sudo: true

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages